//=============================================================================
//
// file :         PcoClass.h
//
// description :  Include for the PcoClass root class.
//                This class is the singleton class for
//                the Pco device class.
//                It contains all properties and methods which the 
//                Pco requires only once e.g. the commands.
//			
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL: $
//
// CVS only:
// $Source:  $
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#ifndef _PCOCLASS_H
#define _PCOCLASS_H

#include <tango.h>
#include <Pco.h>


namespace Pco_ns
{//=====================================
//	Define classes for attributes
//=====================================
class pixelScanRateAttrib: public Tango::Attr
{
public:
	pixelScanRateAttrib():Attr("pixelScanRate", Tango::DEV_STRING, Tango::READ_WRITE) {};
	~pixelScanRateAttrib() {};
	
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
	{(static_cast<Pco *>(dev))->read_pixelScanRate(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
	{(static_cast<Pco *>(dev))->write_pixelScanRate(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
	{return (static_cast<Pco *>(dev))->is_pixelScanRate_allowed(ty);}
};

class shutterModeAttrib: public Tango::Attr
{
public:
	shutterModeAttrib():Attr("shutterMode", Tango::DEV_STRING, Tango::READ_WRITE) {};
	~shutterModeAttrib() {};
	
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
	{(static_cast<Pco *>(dev))->read_shutterMode(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
	{(static_cast<Pco *>(dev))->write_shutterMode(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
	{return (static_cast<Pco *>(dev))->is_shutterMode_allowed(ty);}
};

//=========================================
//	Define classes for commands
//=========================================
class TalkClass : public Tango::Command
{
public:
	TalkClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	TalkClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~TalkClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Pco *>(dev))->is_Talk_allowed(any);}
};



//
// The PcoClass singleton definition
//

class
#ifdef WIN32
	__declspec(dllexport)
#endif
	PcoClass : public Tango::DeviceClass
{
public:
//	properties member data

//	add your own data members here
//------------------------------------

public:
	Tango::DbData	cl_prop;
	Tango::DbData	cl_def_prop;
	Tango::DbData	dev_def_prop;

//	Method prototypes
	static PcoClass *init(const char *);
	static PcoClass *instance();
	~PcoClass();
	Tango::DbDatum	get_class_property(string &);
	Tango::DbDatum	get_default_device_property(string &);
	Tango::DbDatum	get_default_class_property(string &);
	
protected:
	PcoClass(string &);
	static PcoClass *_instance;
	void command_factory();
	void get_class_property();
	void attribute_factory(vector<Tango::Attr *> &);
	void write_class_property();
	void set_default_property();
	string get_cvstag();
	string get_cvsroot();

private:
	void device_factory(const Tango::DevVarStringArray *);
};


}	//	namespace Pco_ns

#endif // _PCOCLASS_H
