static const char *RcsId = "$Id $";
//+=============================================================================
//
// file :         PcoStateMachine.cpp
//
// description :  C++ source for the Pco and its alowed 
//                methods for commands and attributes
//
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL: $
//
// CVS only:
// $Source:  $
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include "Pco.h"
#include <PcoClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace Pco_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		Pco::is_shutterMode_allowed
// 
// description : 	Read/Write allowed for shutterMode attribute.
//
//-----------------------------------------------------------------------------
bool Pco::is_shutterMode_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Pco::is_pixelScanRate_allowed
// 
// description : 	Read/Write allowed for pixelScanRate attribute.
//
//-----------------------------------------------------------------------------
bool Pco::is_pixelScanRate_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		Pco::is_Talk_allowed
// 
// description : 	Execution allowed for Talk command.
//
//-----------------------------------------------------------------------------
bool Pco::is_Talk_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

}	// namespace Pco_ns
