static const char *RcsId = "$Id $";
//+=============================================================================
//
// file :         PerkinElmerStateMachine.cpp
//
// description :  C++ source for the PerkinElmer and its alowed 
//                methods for commands and attributes
//
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL: $
//
// CVS only:
// $Source:  $
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include <PerkinElmer.h>
#include <PerkinElmerClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace PerkinElmer_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		PerkinElmer::is_correctionMode_allowed
// 
// description : 	Read/Write allowed for correctionMode attribute.
//
//-----------------------------------------------------------------------------
bool PerkinElmer::is_correctionMode_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PerkinElmer::is_keepFirstImage_allowed
// 
// description : 	Read/Write allowed for keepFirstImage attribute.
//
//-----------------------------------------------------------------------------
bool PerkinElmer::is_keepFirstImage_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PerkinElmer::is_gain_allowed
// 
// description : 	Read/Write allowed for gain attribute.
//
//-----------------------------------------------------------------------------
bool PerkinElmer::is_gain_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		PerkinElmer::is_StartAcqOffsetImage_allowed
// 
// description : 	Execution allowed for StartAcqOffsetImage command.
//
//-----------------------------------------------------------------------------
bool PerkinElmer::is_StartAcqOffsetImage_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		PerkinElmer::is_StartAcqGainImage_allowed
// 
// description : 	Execution allowed for StartAcqGainImage command.
//
//-----------------------------------------------------------------------------
bool PerkinElmer::is_StartAcqGainImage_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

}	// namespace PerkinElmer_ns
