static const char *RcsId = "$Id $";
//+=============================================================================
//
// file :         ProsilicaCCDStateMachine.cpp
//
// description :  C++ source for the ProsilicaCCD and its alowed 
//                methods for commands and attributes
//
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL: $
//
// CVS only:
// $Source:  $
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#ifdef WIN32
#include <tango.h>
#endif

#include <ProsilicaCCD.h>
#include <ProsilicaCCDClass.h>

#ifndef WIN32
#include <tango.h>
#endif

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace ProsilicaCCD_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================




//=================================================
//		Commands Allowed Methods
//=================================================


}	// namespace ProsilicaCCD_ns
