//=============================================================================
//
// file :        XpadPixelDetector.h
//
// description : Include for the XpadPixelDetector class.
//
// project :	XPAD Pixel Detector from Lima
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL: $
//
// CVS only:
// $Source:  $
// $Log:  $
//
// copyleft :    Synchrotron SOLEIL 
//               L'Orme des merisiers - Saint Aubin
//		 BP48 - 91192 Gif sur Yvette
//               FRANCE
//
//=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================
#ifndef _XPADPIXELDETECTOR_H
#define _XPADPIXELDETECTOR_H

#include <tango.h>
#include "HwInterface.h"
#include "CtControl.h"
#include "CtAcquisition.h"
#include "CtImage.h"

#include <XpadInterface.h>

#include "Factory.h"
//using namespace Tango;

/**
 * @author	$Author:  $
 * @version	$Revision:  $
 */

 //	Add your own constant definitions here.
 //-----------------------------------------------

using namespace lima;
using namespace std;

namespace XpadPixelDetector_ns
{

/**
 * Class Description:
 * This is the Xpad 3.2 (PCIe) Pixel Detector device, which uses Lima
 */

/*
 *	Device States Description:
*  Tango::INIT :
*  Tango::STANDBY :
*  Tango::RUNNING :
*  Tango::FAULT :
 */


class XpadPixelDetector: public Tango::Device_4Impl
{
public :
	//	Add your own data members here
	//-----------------------------------------


	//	Here is the Start of the automatic code generation part
	//-------------------------------------------------------------	
/**
 *	@name attributes
 *	Attribute member data.
 */
//@{
		Tango::DevULong	*attr_deadTime_read;
		Tango::DevULong	attr_deadTime_write;
		Tango::DevULong	*attr_init_read;
		Tango::DevULong	attr_init_write;
		Tango::DevULong	*attr_shutter_read;
		Tango::DevULong	attr_shutter_write;
		Tango::DevULong	*attr_ovf_read;
		Tango::DevULong	attr_ovf_write;
		Tango::DevULong	*attr_mode_read;
		Tango::DevULong	attr_mode_write;
		Tango::DevULong	*attr_n_read;
		Tango::DevULong	attr_n_write;
		Tango::DevULong	*attr_p_read;
		Tango::DevULong	attr_p_write;
		Tango::DevULong	*attr_gp1_read;
		Tango::DevULong	attr_gp1_write;
		Tango::DevULong	*attr_gp2_read;
		Tango::DevULong	attr_gp2_write;
		Tango::DevULong	*attr_gp3_read;
		Tango::DevULong	attr_gp3_write;
		Tango::DevULong	*attr_gp4_read;
		Tango::DevULong	attr_gp4_write;
		Tango::DevUShort	*attr_dacl_read;
		Tango::DevUShort	attr_dacl_write;
		Tango::DevUShort	*attr_ithl_read;
		Tango::DevUShort	attr_ithl_write;
//@}

/**
 * @name Device properties
 * Device properties member data.
 */
//@{
/**
 *	Depth of the pixels: can be 2 or 4 (bytes)
 */
	Tango::DevShort	pixelDepth;
/**
 *	Type of Acquisition:
 *	0->slow (readOneImage)
 *	1->fast (getImgSeq)
 */
	Tango::DevShort	acquisitionType;
/**
 *	list of the all config G, that will be used by the command LoadAllConfigG:
 *	CMOS_DSBL
 *	AMP_TP 
 *	ITHH
 *	VADJ
 *	VREF 
 *	IMFP
 *	IOTA 
 *	IPRE
 *	ITHL
 *	ITUNE
 *	IBUFFER
 */
	vector<long>	allConfigG;
//@}

/**
 *	@name Device properties
 *	Device property member data.
 */
//@{
//@}

/**@name Constructors
 * Miscellaneous constructors */
//@{
/**
 * Constructs a newly allocated Command object.
 *
 *	@param cl	Class.
 *	@param s 	Device Name
 */
	XpadPixelDetector(Tango::DeviceClass *cl,string &s);
/**
 * Constructs a newly allocated Command object.
 *
 *	@param cl	Class.
 *	@param s 	Device Name
 */
	XpadPixelDetector(Tango::DeviceClass *cl,const char *s);
/**
 * Constructs a newly allocated Command object.
 *
 *	@param cl	Class.
 *	@param s 	Device name
 *	@param d	Device description.
 */
	XpadPixelDetector(Tango::DeviceClass *cl,const char *s,const char *d);
//@}

/**@name Destructor
 * Only one destructor is defined for this class */
//@{
/**
 * The object destructor.
 */	
	~XpadPixelDetector() {delete_device();};
/**
 *	will be called at device destruction or at init command.
 */
	void delete_device();
//@}

	
/**@name Miscellaneous methods */
//@{
/**
 *	Initialize the device
 */
	virtual void init_device();
/**
 *	Always executed method before execution command method.
 */
	virtual void always_executed_hook();

//@}

/**
 * @name XpadPixelDetector methods prototypes
 */

//@{
/**
 *	Hardware acquisition for attributes.
 */
	virtual void read_attr_hardware(vector<long> &attr_list);
/**
 *	Extract real attribute values for deadTime acquisition result.
 */
	virtual void read_deadTime(Tango::Attribute &attr);
/**
 *	Write deadTime attribute values to hardware.
 */
	virtual void write_deadTime(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for init acquisition result.
 */
	virtual void read_init(Tango::Attribute &attr);
/**
 *	Write init attribute values to hardware.
 */
	virtual void write_init(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for shutter acquisition result.
 */
	virtual void read_shutter(Tango::Attribute &attr);
/**
 *	Write shutter attribute values to hardware.
 */
	virtual void write_shutter(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for ovf acquisition result.
 */
	virtual void read_ovf(Tango::Attribute &attr);
/**
 *	Write ovf attribute values to hardware.
 */
	virtual void write_ovf(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for mode acquisition result.
 */
	virtual void read_mode(Tango::Attribute &attr);
/**
 *	Write mode attribute values to hardware.
 */
	virtual void write_mode(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for n acquisition result.
 */
	virtual void read_n(Tango::Attribute &attr);
/**
 *	Write n attribute values to hardware.
 */
	virtual void write_n(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for p acquisition result.
 */
	virtual void read_p(Tango::Attribute &attr);
/**
 *	Write p attribute values to hardware.
 */
	virtual void write_p(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for gp1 acquisition result.
 */
	virtual void read_gp1(Tango::Attribute &attr);
/**
 *	Write gp1 attribute values to hardware.
 */
	virtual void write_gp1(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for gp2 acquisition result.
 */
	virtual void read_gp2(Tango::Attribute &attr);
/**
 *	Write gp2 attribute values to hardware.
 */
	virtual void write_gp2(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for gp3 acquisition result.
 */
	virtual void read_gp3(Tango::Attribute &attr);
/**
 *	Write gp3 attribute values to hardware.
 */
	virtual void write_gp3(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for gp4 acquisition result.
 */
	virtual void read_gp4(Tango::Attribute &attr);
/**
 *	Write gp4 attribute values to hardware.
 */
	virtual void write_gp4(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for dacl acquisition result.
 */
	virtual void read_dacl(Tango::Attribute &attr);
/**
 *	Write dacl attribute values to hardware.
 */
	virtual void write_dacl(Tango::WAttribute &attr);
/**
 *	Extract real attribute values for ithl acquisition result.
 */
	virtual void read_ithl(Tango::Attribute &attr);
/**
 *	Write ithl attribute values to hardware.
 */
	virtual void write_ithl(Tango::WAttribute &attr);
/**
 *	Read/Write allowed for deadTime attribute.
 */
	virtual bool is_deadTime_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for init attribute.
 */
	virtual bool is_init_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for shutter attribute.
 */
	virtual bool is_shutter_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for ovf attribute.
 */
	virtual bool is_ovf_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for mode attribute.
 */
	virtual bool is_mode_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for n attribute.
 */
	virtual bool is_n_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for p attribute.
 */
	virtual bool is_p_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for gp1 attribute.
 */
	virtual bool is_gp1_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for gp2 attribute.
 */
	virtual bool is_gp2_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for gp3 attribute.
 */
	virtual bool is_gp3_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for gp4 attribute.
 */
	virtual bool is_gp4_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for dacl attribute.
 */
	virtual bool is_dacl_allowed(Tango::AttReqType type);
/**
 *	Read/Write allowed for ithl attribute.
 */
	virtual bool is_ithl_allowed(Tango::AttReqType type);
/**
 *	Execution allowed for LoadFlatConfig command.
 */
	virtual bool is_LoadFlatConfig_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for LoadAllConfigG command.
 */
	virtual bool is_LoadAllConfigG_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for LoadConfigG command.
 */
	virtual bool is_LoadConfigG_allowed(const CORBA::Any &any);
/**
 *	Execution allowed for LoadAutoTest command.
 */
	virtual bool is_LoadAutoTest_allowed(const CORBA::Any &any);
/**
 * Load a Flat config, for each pixel
 *	@param	argin	Flat value
 *	@exception DevFailed
 */
	void	load_flat_config(Tango::DevULong);
/**
 * Load all the Registers configs (cmos,amptp,itth ....) with default xpad values, for each chip
 *	@exception DevFailed
 */
	void	load_all_config_g();
/**
 * Load a specific Register config, with the wanted value, for each chip.
 *	register can be:
 *	0->CMOS_DSBL
 *	1->AMP_TP
 *	2->ITHH
 *	3->VADJ
 *	4->VREF
 *	5->IMFP
 *	6->IOTA
 *	7->IPRE
 *	8->ITHL
 *	9->ITUNE
 *	10->IBUFFER
 *	@param	argin	register,value
 *	@exception DevFailed
 */
	void	load_config_g(const Tango::DevVarULongArray *);
/**
 * Load a known value to the pixel counters.
 *	@param	argin	value to be loaded
 *	@exception DevFailed
 */
	void	load_auto_test(Tango::DevULong);

/**
 *	Read the device properties from database
 */
	 void get_device_property();
//@}

	//	Here is the end of the automatic code generation part
	//-------------------------------------------------------------	



protected :	
	//	Add your own data members here
	//-----------------------------------------

	bool 			m_is_device_initialized ;
	stringstream	m_status_message;

	void set_all_f_parameters();

	//lima OBJECTS
	XpadInterface* 		m_hw;
	CtControl*			m_ct;
};

}	// namespace_ns

#endif	// _XPADPIXELDETECTOR_H
